server:
  port: ${PORT:6000}
spring:
  application:
    name: "ums_auth_service"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: ${DRIVER_CLASS}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

app:
  jwt-config:
    secret-key: ${SECRET_KEY}
